version: "3.7"
services: 
  db: 
    image: postgres
    environment:
      POSTGRES_USER: postgres
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    # This won't be necessary if we only need our backend CONTAINER to access postgres since the Dockerfile of postgres already EXPOSE port 54321 - TESTED
#    ports:
#      - "5432:5432"
  app:
    image: "zng/express-backend:1.0"
    deploy:
      replicas: 10
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"

    command: ["node", "index.js"]
    depends_on:
      - db




