version: "3.7"
services: 
  db: 
    image: postgres
    environment:
      POSTGRES_USER: postgres
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    # This won't be necessary if we only need our backend CONTAINER to access postgres since the Dockerfile of postgres already EXPOSE port 54321
    ports:
      - "5432:5432"
#  app:
#    build: .
#    ports:
#      - "3000:3000"
#    command: [sh, -c, "sleep 10 && npm test"]
#    depends_on:
#      - db



